### ISSUE TITLE
allowing alias definition

### ISSUE THREAD

**Issue by asfktz** [tnrich/atom-node-requirer#3]
First of all, thank you so much for porting node-requirer to atom. 
This is such a such a life saver, I used it everyday in sublime

one feature I really miss is the ability to define aliases, like this:

![node-req-alias](https://cloud.githubusercontent.com/assets/199747/16364149/24bcc65a-3be9-11e6-95d8-e500a8a25def.gif)

the way to do it in sublime, is by overriding the settings file:

``` js
{
    // Requiring an item that matches a key in the dictionary
    // will transform the rendered require to the value.
    // E.g. var _ = require('lodash') if {'lodash': '_'}
    "alias": {
        "lodash": "_",
        "react": "React",
        "jquery": "$"
    }
}
```

Can you please consider adding this feature?
I will definitely appreciate it

Cheers 
Asaf Katz

**Comment by tnrich** [comment]
Hey @asfktz, thanks for reaching out. I don't have a ton of time to dedicate to the project, but I'll see what I can do. I didn't ever use the alias functionality of the original node-requirer, but it doesn't seem like it'd be too tough to implement. (of course PR's are very welcome :) )

Cheers!

**Comment by tnrich** [comment]
Hey @asfktz, version 0.1.6 adds the ability to define a JSON alias list. Let me know if this fits what you want. 

Cheers,
Thomas

**Comment by einarlove** [comment]
Mad props for porting this. Lifesaver!
I found one issue when porting my aliases where you don't allow non [a-zA-Z] characters.

My alias `"react-redux": "{ connect }"` gives the error

> Error in node-requirer alias list. Make sure you are using valid 
> `:SyntaxError. Unexpected Token {`

**Comment by tnrich** [comment]
Hmm interesting I'll take a look when I get a second.

**Comment by tnrich** [comment]
Okay, I tweaked it and it should be working as you expect now.

**Comment by tnrich** [comment]
![image](https://cloud.githubusercontent.com/assets/2730609/17185490/20d26bac-53e6-11e6-8588-895b6009ba02.png)

![image](https://cloud.githubusercontent.com/assets/2730609/17185478/115f7552-53e6-11e6-9f21-cd154cc1ef4a.png)

**Comment by tnrich** [comment]
@asfktz and @einarlove , I'm gonna close this because I think it's been fixed. Feel free to re-open if you find any more issues.
