### ISSUE TITLE
Retain filename casing

### ISSUE THREAD

**Issue by einarlove** [tnrich/atom-node-requirer#4]
I see you [convert the filename to cameCase](https://github.com/tnrich/atom-node-requirer/blob/master/lib/fuzzy-finder-view.coffee#L67) so that `webpack.config.js` and `data-dump.json` converts to feasible names, but this ignores the files title casing. If the file is named `Direct-Open.js` it should be `import DirectOpen from ...`, not `import directOpen...`.

**Comment by einarlove** [comment]
Very relevant for those using [React](https://facebook.github.io/react/) which demands component names start with uppercase.

``` jsx
import MyButton from './MyButton'
<MyButton />
```

**Comment by tnrich** [comment]
Hey @einarlove , I had noticed this issue as well. Would it be enough to camelCase the name no matter what, and then, if if the name was upper case originally, upper case the first letter?

**Comment by tnrich** [comment]
@einarlove I implemented what I said above. Try it out on v0.1.8 :)

**Comment by einarlove** [comment]
Been using it all day and can't find a issue with your fix. Great job @tnrich!

**Comment by tnrich** [comment]
Glad to hear it.
